### ISSUE TITLE
Define error codes

### ISSUE THREAD

**Issue by Ironjanowar** [Ironjanowar/refraner_server#5]
Specially for `/api/refran/<refran_id>/vote/user/<user_id>` where a `404` status code is ambiguous since we can not distinguish if is the user the one that was not found or the refran.

**Comment by Ironjanowar** [comment]
First of all lets see what kind of errors do we have:
- User not found
- Refran not found
- General bad request
- Vote should be between 1 and 5 (should discuss this)

**Comment by Ironjanowar** [comment]
Error body response:
```json
{"error_code": "E-123-1", "reason": "Meh"}
```
Every response should have a **reason** message so the client can identify what is going wrong.

**Error codes:**
- User not found: **E-404-1**
- Refran not found: **E-404-2**
- General bad request: **E-400-1** (_http status code would be **400** so maybe this is not needed_)
- Vote between 1 and 5: **E-400-2**

This is my first time defining error codes so... be gentle XDDD

**Comment by AshidaSRS** [comment]
Maybe remove the `-`:
`E-404-1` -> `E4041`
`E-404-2` -> `E4042`
`E-400-1` -> `E4001`
`E-400-2` -> `E4002`

You are not going to parse them so the `-` are useless.

**Comment by Ironjanowar** [comment]
@AshidaSRS I don't know if parsing would be useful in the future :/, anyways I could parse `E4041` as `User not found` so...

**Comment by rockneurotiko** [comment]
Mmmm I don't really like either way, I would do it like this:

`{"error_code": 404, message: "User not found"}`

If you want to have locales, it can be something like:

`{"error_code": 404, message: "user_not_found"}` and you will take that message as key to get the translation.

Doing that generic and not adding more error codes makes that all the apps working with your server don't need to know all your error codes, just the basic ones and how to display the errors.

**Comment by Ironjanowar** [comment]
@rockneurotiko Nice, is `"error_code"` needed since the `404` is already in the HTTP response?

**Comment by AshidaSRS** [comment]
Yeah but imagine that you will need some info in the message from the backend (idk, it's a guess).
You  don't need the error code in the message if you have it in the reponse but the locales help you to distinguish the "pretty message" and the actual error in the backend like:
```{"error_code": 4041, message: "Refran not found in the db"}```
```{"error_code": 4042, message: "User not found in the db"}```

and in the front use the code to change the display msg if you have multiple types of display.

If you will use a generic display for all of them then yes, use the message to match the msg like:
```{"error_code": 404, message: "user_not_found"}```
or 
```{"error": true, message: "user_not_found"}```

**Comment by Ironjanowar** [comment]
<img src="https://user-images.githubusercontent.com/9699815/38495224-30d32aee-3bf9-11e8-905b-8dda120abfc0.jpg" alt="alt text" width="300px" height="250px">


I'll meditate about this, thank you two!! <3

**Comment by Ironjanowar** [comment]
After meditation, the result is this:

Error body response:
```json
{
   "error_code":123,
   "message":"Log message",
   "errors":{
      "param1":"reason1",
      "param2":"reason2"
   }
}
```
Example of user not found from a `/api/refran/1/vote/user/123` request:
```json
{
   "error_code":404,
   "message":"User ID 123 was not found",
   "errors":{
      "user_id":"not_found"
   }
}
```

Example of user and refran not found from a `/api/refran/321/vote/user/123` request:
```json
{
   "error_code":404,
   "message":"User ID 123 and Refran ID 321 were not found",
   "errors":{
      "user_id":"not_found",
      "refran_id":"not_found"
   }
}
```

**Comment by Ironjanowar** [comment]
**Types of errors**
- User _Y_ not found for Refran _X_
- Refran not found
- General bad request
- Vote should be between 1 and 5


**Response Body examples**

_Request:_ `/api/refran/1/vote/user/123`
_Error:_ User 123 not found for Refran 1 (wich exists)
```json
{
   "error_code":404,
   "message":"Telegram User 123 not found for Refran ID 1",
   "errors":{
      "tg_user_id":"not_found"
   }
}
```
_Request:_ `/api/refran/321/vote/user/123`
_Error:_ User 123 not found for Refran 321 that was not found neither
**IMPORTANT:** Users don't exist by their own, they appear in the _votes_ table, this means that if the refran is not found the user wont be found either.
```json
{
   "error_code":404,
   "message":"Telegram User 123 not found for Refran ID 321",
   "errors":{
      "refran_id":"not_found"
   }
}
```
_Request:_ `/api/refran/321`
_Error:_ Refran ID not found
```json
{
   "error_code":404,
   "message":"Refran ID 321 not found",
   "errors":{
      "refran_id":"not_found"
   }
}
```
_Request:_ `/api/refran/1/vote/user/123`
_Error:_ Bad Request
```json
{
   "error_code":400,
   "message":"Bad Request"
}
```
_Request:_ `/api/refran/1/vote/user/123` with `vote = 8`
_Error:_ Vote should be between 1 and 5 both included
```json
{
   "error_code":409,
   "message":"Vote should be between 1 and 5, received vote is 8",
   "errors":{
      "vote":"not_in_range"
   }
}
```
